name: CI/CD Pipeline - Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Verification des fichiers
        run: |
          echo "Fichiers presents :"
          ls -la
          test -f index.html && echo "index.html trouve" || echo "ERREUR"

  deploy:
    name: Deploy vers GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Deploiement sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
